apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  # 이름을 허용 목록을 사용한다는 의미로 바꾸는 것이 더 명확합니다.
  name: restrict-hostpath-to-allowed-list
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: allowed-hostpath-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "The HostPath `{{element.hostPath.path}}` is not in the allowed list. Please use an approved path."
        foreach:
        - list: "request.object.spec.volumes"
          preconditions:
            all:
              - key: "{{element.hostPath}}"
                operator: NotEquals
                value: ""
          deny:
            conditions:
              any:
                - key: "{{element.hostPath.path}}"
                  operator: AnyNotIn
                  value:
                    - "/var/log/pods"
                    - "/mnt/data"