apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-hostpath-volumes
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: no-hostpath-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "The HostPath `{{element.hostPath.path}}` is not in the allowed list. Please use an approved path."
        # foreach: 리소스 내의 배열(리스트)을 순회하며 각 항목에 대해 검증 로직을 적용합니다.
        foreach:
          # list: 순회할 대상 필드를 지정합니다. 여기서는 파드의 볼륨 목록입니다.
          list: "request.object.spec.volumes"
          # preconditions: 이 순회 로직을 적용하기 위한 전제조건입니다.
          # 이 조건을 만족하는 항목에 대해서만 아래 deny 로직을 실행합니다.
          preconditions:
            all:
              # 'element'는 순회 중인 현재 항목(여기서는 각 volume)을 의미합니다.
              # 'hostPath' 필드가 존재하는 볼륨에만 이 규칙을 적용합니다.
              - key: "{{element.hostPath}}"
                operator: NotEquals
                value: ""
          # deny: 아래 조건이 참일 경우, 해당 요청을 거부합니다.
          deny:
            conditions:
              any:
                # 'element.hostPath.path' (현재 검사 중인 볼륨의 hostPath 경로)가
                # 아래 'value' 목록에 포함되어 있지 않으면 '참'이 됩니다.
                - key: "{{element.hostPath.path}}"
                  operator: AnyNotIn
                  # ✅ 이 곳에 허용할 HostPath 경로 목록을 정의합니다.
                  value:
                    - "/var/log/pods"
                    - "/mnt/data"